import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import { TodoProvider } from "@/store/todo-context";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-Do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-screen leading-relaxed tracking-wide`}>
        <TodoProvider>
          {children}
        </TodoProvider>
      </body>
    </html>
  );
}
